name: Check Markdown files correctness

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Extract links from Markdown texts and check if they are alive
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # for v1.10.0
      with:
        args: --base --verbose --no-progress './**/*.md' './**/*.html'
  # Lint Markdown files
  # Uses: a custom configuration file
  markdown-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DavidAnson/markdownlint-cli2-action@v15
      with:
        globs: "**/*.md"
  # Spellcheck Markdown files using `retext` and `remark`
  # Uses: a custom dictionary file
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: tbroadley/spellchecker-cli-action@v1
      with:
        # No need to use a dictionary file with the disabled spell plugin 
        # dictionaries: '.github/workflows/dictionary.txt'
        files: "'content/**/*.md'"
        quiet: true
        plugins: "indefinite-article repeated-words syntax-mentions syntax-urls"
